### PR TITLE
Break up core into its logical components

### PR DESCRIPTION
**Pull request by kellysutton**
Consider merging this after https://github.com/imgix/imgix.js/pull/55 has landed.

### CODE REVIEW

**Comment by jayeb** [comment]
Have you tested whether the doc-compiling still works after this re-org?

**Comment by kellysutton** [comment]
Doc compiling still works, but a few things are moved around to reflect the new ordering of the files. These should really be alphabetized. Any experience doing that with grunt-jsdoc?

An aside: We expose a lot of public APIs through this thing. We should take a pass to make everything private that does not need to be public.

**Comment by kellysutton** [comment]
Based on this thread, it seems like sorting should be possible and the default behavior: https://groups.google.com/forum/#!topic/jsdoc-users/xlZ1E2PgMYU

I'll look for the configuration change needed to make this a reality.

**Comment by kellysutton** [comment]
b70bd54 alphabetizes method names so that we have a consistent ordering of these methods going forward.

**Comment by jayeb** [comment]
Rebased and made sure recent changes to `core.js` made it to their respective files. @kellysutton mind giving this a once-over before I merge it?

**Pull request merged**
