### PR TITLE
Update polyfills.js

### PR DESCRIPTION
**Pull request by matiasnombarasco**
I found this patch useful to deal with prototypeJs, that library updates the native filter method to use the findAll prototypeJs method, which is not correct, so in order to prevent to this plugins to fail in some circunstancies I found this useful. 

Please review and let me know if we can merge into the main branch. Otherwise we might diverge from the original repo and use our own fork. 

Cheers

### CODE REVIEW

**Comment by paulstraw** [comment]
I believe this would break other plugins that depend on Prototype's weird `Array.prototype.filter` behavior. @jayeb, I know we've actually discussed this Prototype.js issue before, and I think we had come to the conclusion that we should just define these as methods in the app and call them directly instead of overriding prototypes on native objects. I'm still leaning towards that. Thoughts?

**Comment by paulstraw** [comment]
Either way @matiasnombarasco, we'll definitely get this sorted, it just might be in a slightly different fashion. Thanks for the PR!

**Comment by matiasnombarasco** [comment]
Hi @paulstraw , I guess take the approach to define the filter method to the local scope of the function will be the best thing to do! 

Please keep me posted about any progress. Feel free to close and remove the pull request. 

Cheers

**Comment by paulstraw** [comment]
Hey @matiasnombarasco, after some internal discussion, we're actually going to go ahead and merge this in. I'll get it released as version 2.2.2 shortly.

**Comment by paulstraw** [comment]
Alrighty, should be all set now as [2.2.2](https://github.com/imgix/imgix.js/releases/2.2.2)! Thanks again.

**Pull request merged**
