### PR TITLE
Prune a bunch of tokenizing and MD5 code

### PR DESCRIPTION
**Pull request by jayeb**
@zacman85 No rush, but can I get a sanity-check review on this when you have time?

### CODE REVIEW

**Comment by kellysutton** [comment]
Is the reason for crushing the MD5 stuff because we're trying to not sign stuff at this level, due to the security leakage?

**Comment by zacman85** [comment]
@kellysutton That is essentially the reasoning. @jason This looks good to me.

**Comment by kellysutton** [comment]
Cool. Since it's a breaking change, it's a good time to bump to 1.1.0.

**Comment by jayeb** [comment]
My thoughts exactly. 1.0.x is dead! Long live 1.0.x!

**Comment by zacman85** [comment]
Good point. Agreed on the version bump.

**Pull request merged**
